package cs203t10.ryver.market.trade.view;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import cs203t10.ryver.market.trade.Trade.Status;
import cs203t10.ryver.market.trade.Trade.Action;
import lombok.*;

@Data
@AllArgsConstructor @NoArgsConstructor
public class TradeView {

    private Action action;

    private String symbol;

    private Integer quantity;

    private Double bid;

    private Double ask;

    private Double avgPrice;

    private Integer filledQuantity;

    @JsonFormat(shape = JsonFormat.Shape.NUMBER)
    private Date date;

    private Integer accountId;

    private Integer customerId;

    private Status status;

}

/**
  "id": (auto-generated by your api),
  "action":"buy", (specify "sell" for selling)
  "symbol":"A17U",
  "quantity":1000, (in multiples of 100)
  "bid":3.28, (specify 0.0 for market order, ignored if action is "sell")
  "ask":3.27, (specify 0.0 for market order, ignored if action is "buy")
  "avg_price":3.30 (the average filled price, as one trade can be matched by several other trades)
  "filled_quantity":0;
  "date": (submitted time in Unix timestamp, expired after 5pm of the day),
  account_id"":1234, (account to debit or to deposit fund)
  "customer_id":1234, (submitter of the trade)
  "status":"open" (or "filled", "partial-filled", "cancelled", "expired")
*/
