server:
  port: 8086
  error:
    include-stacktrace: never

spring:
  application:
    name: ryver-market
  datasource:
    url: jdbc:h2:file:./data/market;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761}/eureka
  instance:
    prefer-ip-address: true

