### Check root route
GET http://localhost:8086/

### Get default stocks
GET http://localhost:8086/stocks

### Get one stock
GET http://localhost:8086/stocks/A17U

###
GET http://localhost:8080/customers
Authorization: Basic manager_1 01_manager_01

### Create new trade
POST http://localhost:8086/trades
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

{
    "action":"buy",
    "symbol":"A17E",
    "quantity":1000,
    "bid":3.28,
    "ask":3.27,
    "avg_price":3.30,
    "filled_quantity":0,
    "account_id":1234,
    "customer_id":7,
    "status":"open"
}

### Get trade by id
GET http://localhost:8086/trades/9
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg
