### Get default stocks as customer
GET http://localhost:8086/stocks
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

### Get one stock as manager
GET http://localhost:8086/stocks/A17U
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDM1NDg3NTh9.C_VgHqTZAQf_u4digKkBUhIh-5Nuj5yZWZPoBg4woc8QfUVc8wsVhgt2sRNiIUmJZyrzvcqy4lwqQXAxkaI3Ew

### Get one stock as customer
GET http://localhost:8086/stocks/A17U
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

### Get non-existent stock
GET http://localhost:8086/stocks/A17V
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

### Create new trade
POST http://localhost:8086/trades
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnb29kX3VzZXJfMSIsInVpZCI6NCwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYwNDMyNjkwM30.nFIjA1Vs_euzygcxKSaQD52MKH1hOF8AjY3rrstbav-BPHsb-EQE78w-NSJZU7GxGQZDrh6fycT9BbECLEueAA

{
    "action":"buy",
    "symbol":"M44U",
    "quantity": 100,
    "bid":100,
    "ask":0,
    "avg_price":0,
    "account_id":1,
    "customer_id": 4
}

### Create new trade with non-existent stock

### View own portolio
GET http://localhost:8086/portfolio
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6MTksImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2MDM5MDI3MzN9.hCS-76w4AC0n5t1SFXeIO9b8IwcK7WZ3oTnc_M1XE9ALn_CkWIJl4C_Wjo0O4mXPLvwWPLlxjHVgnpeHcD3OQQ

### Get user trades
GET http://localhost:8086/trades
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

### Get trade by id
GET http://localhost:8086/trades/61
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6MTksImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2MDM5MDI3MzN9.hCS-76w4AC0n5t1SFXeIO9b8IwcK7WZ3oTnc_M1XE9ALn_CkWIJl4C_Wjo0O4mXPLvwWPLlxjHVgnpeHcD3OQQ

### Get trade by id, not the user's trade
GET http://localhost:8086/trades/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdGFuIiwidWlkIjo3LCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjAzMTg2MDgyfQ.dQVlJDKEJ25ZhWm7LMzLlg9UlPTavC3xwThBELo-dBXPk0fKWmrwDZghIn_boDEY2wDGIYjcJWvZoTPBf7yPBg

### Cancel trade by id
PUT  http://localhost:8086/trades/104
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6MTksImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2MDM5MDI3MzN9.hCS-76w4AC0n5t1SFXeIO9b8IwcK7WZ3oTnc_M1XE9ALn_CkWIJl4C_Wjo0O4mXPLvwWPLlxjHVgnpeHcD3OQQ

